# -*- coding: utf-8 -*-
"""01-Pizza_Toppings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/176BKxKSX9zQegqAufG4wHhCTWN9AFNZR
"""

age = "\nInput 'quit' when you are done."
age += "\nWhat is your age? "
message = " "
while message !="quit":
    message = input(age)
    if int(message) < 3:
     print("Your ticket is free")
    elif int(message) <= 12:
     print("Your ticket costs 10$")
    elif int(message) > 12:
     print("Your ticket costs 15$")
