# -*- coding: utf-8 -*-
"""03-Infinity.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nRco4WbAoLsR3q3GOEjeMCo28y91xiJ4
"""

x = 1
while x <= 1:
 print(x)